receivers:
  filelog:
    include:
      - /var/lib/docker/containers/*/*-json.log
    start_at: end
    include_file_path: true
    operators:
      - type: json_parser
        parse_from: body
      - type: move
        from: attributes.log
        to: body
      - type: filter
        expr: 'body matches "trace_id="'

processors:
  batch:
    timeout: 1s
    send_batch_size: 256
  resource:
    attributes:
      - key: service.name
        action: upsert
        value: be-forum
      - key: deployment.environment
        action: upsert
        value: ${env:OTEL_ENVIRONMENT}

exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resource, batch]
      exporters: [otlphttp]
